### ISSUE TITLE
TypeError: jsonrpc.parseObject is not a function

### ISSUE THREAD

**Issue by DRC9702** [teambition/jsonrpc-lite#1]
Hello! 

I'm trying to create a reactjs project built on top of [kadence](https://github.com/kadence/kadence) which uses this package as a dependency. However, I'm getting this error:
```
Uncaught TypeError: jsonrpc.parseObject is not a function
```
whenever the parseObject function is called. Without using react, everything works fine in browser using normal javascript. I don't see anything wrong with the require statement:
```
const jsonrpc = require('jsonrpc-lite');
```
Is there a reason this is failing or any insight that can be provided? Thank you very much. :)

**Comment by zensh** [comment]
the variable `jsonrpc` may be overwritten in your program

**Comment by DRC9702** [comment]
Hi @zensh, I believe it may have to do with how the exports are done. Changing the following line in `jsonrpc.mjs` fixes the issue for me, albeit I have to change how I require the module to `require('jsonrpc-lite).jsonrpc`.
```
// export { JsonRpc, JsonRpcError, jsonrpc as default } // Swap this line for the one below
module.exports = { JsonRpc, JsonRpcError, jsonrpc}
```
Is there a better recommended fix for this?

**Comment by zensh** [comment]
please try v1.3.1
