### ISSUE TITLE
Unable to use RpcStatusType enum

### ISSUE THREAD

**Issue by makoven** [teambition/jsonrpc-lite#13]
RpcStatusType is defined in jsonrpc.ts, but not in jsonrpc.js. So this code throws an error:

```js
import { RpcStatusType } from "jsonrpc-lite";
...
switch (req.type) {
  case RpcStatusType.invalid:
...
```

**Comment by antongolub** [comment]
Moreover, if we'd try to use this enum with `ts-jest` it will also be `undefined`. (https://github.com/kulshekhar/ts-jest/issues/281).

I guess, we should make enum to be const:
```
export const enum RpcStatusType {
  request = 'request',
  notification = 'notification',
  success = 'success',
  error = 'error',
  invalid = 'invalid',
}
```

**Comment by antongolub** [comment]
@junyuanqi, @zensh could anybody review the fix?

**Comment by zensh** [comment]
@antongolub Thank you very much, `v2.1.0` released.
