### ISSUE TITLE
Cannot find module 'tslib'

### ISSUE THREAD

**Issue by ivankravets** [teambition/jsonrpc-lite#4]
* https://github.com/teambition/jsonrpc-lite/blob/master/jsonrpc.js#L7
* https://github.com/teambition/jsonrpc-lite/blob/master/package.json#L26

New v2.0.0 totally broke our application. Why do you need `tslib` in production?

P.S: Revert back to the previous version.

**Comment by zensh** [comment]
Sorry (⊙︿⊙)
v2.0.1 released
