### ISSUE TITLE
Incorrect type of params

### ISSUE THREAD

**Issue by VDGSecurity** [teambition/jsonrpc-lite#5]
According to the typings file it is allowed to supply a `string | number | boolean | object | null` to the params attribute (`RpcParams`). However according to the specs and the implementation, only objects or arrays are allowed.

I guess 
 3 ```declare type RpcParams = defined | defined[];```
should be
 3 ```declare type RpcParams = object | defined[];```

**Comment by zensh** [comment]
Yes, I will fix it tonight
