### ISSUE TITLE
Does `parseObject` return an array of a single item?

### ISSUE THREAD

**Issue by pronebird** [teambition/jsonrpc-lite#6]
The README states that `parseObject` returns either array or single object, but `d.ts` points out that the function returns a single `IParsedObject`. Who's right and who's wrong?

> jsonrpc.parseObject(message)
> 
> Takes a JSON-RPC 2.0 payload (Object) and tries to parse it into a JSON. If successful, determine what object is it (response, notification, success, error, or invalid), and return it's type and properly formatted object.
> 
> message: {Object}
> return an array, or an object same as jsonrpc.parse.

**Comment by zensh** [comment]
It returns a single item.

**Comment by pronebird** [comment]
Thanks for updating the README @zensh
